spring.application.name=hrms
hrms.company.name = Agnie Consulting
hrms.company.location = Chennai
hrms.support.email = hrms@agnieconsulting.co.in
hrms.office.timing = 9 AM to 6 PM
hrms.itsupport.email = itsupport@agnieconsulting.co.in
hrms.support.department = IT Department
